//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friends.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.CommentReplies = new HashSet<CommentReply>();
        }
    
        public int CommentId { get; set; }
        public int ReceiverId { get; set; }
        public int SenderId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual ICollection<CommentReply> CommentReplies { get; set; }
    }
}
