//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friends.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendsEntities: DbContext
    {
        public FriendsEntities()
            : base("name=FriendsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FriendRelation> FriendRelations { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<GroupFriend> GroupFriends { get; set; }
        public DbSet<Mind> Minds { get; set; }
        public DbSet<PrivateGroup> PrivateGroups { get; set; }
        public DbSet<Record> Records { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Visit> Visits { get; set; }
    }
}
