//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupFriend
    {
        public int GroupId { get; set; }
        public int UserId { get; set; }
        public System.DateTime JoinTime { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
