//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Books = new HashSet<Book>();
            this.Books1 = new HashSet<Book>();
            this.Books2 = new HashSet<Book>();
            this.Books3 = new HashSet<Book>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> SortNum { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Book> Books1 { get; set; }
        public virtual ICollection<Book> Books2 { get; set; }
        public virtual ICollection<Book> Books3 { get; set; }
    }
}
