//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderComment
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public string ReaderName { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
