//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friends.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupFriends = new HashSet<GroupFriend>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string Category { get; set; }
        public int CreaterId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<GroupFriend> GroupFriends { get; set; }
    }
}
