//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityBookInfo
    {
        public EntityBookInfo()
        {
            this.BookBasicInfoes = new HashSet<BookBasicInfo>();
            this.EntityProfits = new HashSet<EntityProfit>();
            this.Orders = new HashSet<Order>();
            this.UserComments = new HashSet<UserComment>();
            this.UserScores = new HashSet<UserScore>();
        }
    
        public int BookId { get; set; }
        public string Author { get; set; }
        public int PublisherId { get; set; }
        public System.DateTime PublishDate { get; set; }
        public decimal Price { get; set; }
        public int BasicId { get; set; }
        public int Count { get; set; }
        public string ISBN { get; set; }
        public decimal BuyPrice { get; set; }
    
        public virtual ICollection<BookBasicInfo> BookBasicInfoes { get; set; }
        public virtual BookBasicInfo BookBasicInfo { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<EntityProfit> EntityProfits { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<UserScore> UserScores { get; set; }
    }
}
