//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusAcademy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FocusBookEntities : DbContext
    {
        public FocusBookEntities()
            : base("name=FocusBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookBasicInfo> BookBasicInfoes { get; set; }
        public virtual DbSet<BookType> BookTypes { get; set; }
        public virtual DbSet<ChapterUrl> ChapterUrls { get; set; }
        public virtual DbSet<EAuthor> EAuthors { get; set; }
        public virtual DbSet<EBookInfo> EBookInfoes { get; set; }
        public virtual DbSet<EntityBookInfo> EntityBookInfoes { get; set; }
        public virtual DbSet<EntityProfit> EntityProfits { get; set; }
        public virtual DbSet<EProfit> EProfits { get; set; }
        public virtual DbSet<FocusAdmin> FocusAdmins { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PlayManage> PlayManages { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<TotalBookType> TotalBookTypes { get; set; }
        public virtual DbSet<UserComment> UserComments { get; set; }
        public virtual DbSet<UserHouse> UserHouses { get; set; }
        public virtual DbSet<UserProfit> UserProfits { get; set; }
        public virtual DbSet<UserScore> UserScores { get; set; }
        public virtual DbSet<UsersInfo> UsersInfoes { get; set; }
        public virtual DbSet<UsersRole> UsersRoles { get; set; }
        public virtual DbSet<UsersState> UsersStates { get; set; }
    }
}
