//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnswerId { get; set; }
        public int QuestionId { get; set; }
        public string Content { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> Prize { get; set; }
        public Nullable<bool> IsBest { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
