//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBasicInfo
    {
        public BookBasicInfo()
        {
            this.EBookInfoes = new HashSet<EBookInfo>();
            this.EntityBookInfoes = new HashSet<EntityBookInfo>();
        }
    
        public int BasicId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int TypeId { get; set; }
        public string CoverImage { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> ScoreCount { get; set; }
    
        public virtual BookType BookType { get; set; }
        public virtual ICollection<EBookInfo> EBookInfoes { get; set; }
        public virtual ICollection<EntityBookInfo> EntityBookInfoes { get; set; }
    }
}
