//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusAcademy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FocusBookEntities : DbContext
    {
        public FocusBookEntities()
            : base("name=FocusBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookBasicInfo> BookBasicInfoes { get; set; }
        public DbSet<BookType> BookTypes { get; set; }
        public DbSet<ChapterUrl> ChapterUrls { get; set; }
        public DbSet<EAuthor> EAuthors { get; set; }
        public DbSet<EBookInfo> EBookInfoes { get; set; }
        public DbSet<EntityBookInfo> EntityBookInfoes { get; set; }
        public DbSet<EntityProfit> EntityProfits { get; set; }
        public DbSet<EProfit> EProfits { get; set; }
        public DbSet<FocusAdmin> FocusAdmins { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<PlayManage> PlayManages { get; set; }
        public DbSet<Publisher> Publishers { get; set; }
        public DbSet<TotalBookType> TotalBookTypes { get; set; }
        public DbSet<UserComment> UserComments { get; set; }
        public DbSet<UserHouse> UserHouses { get; set; }
        public DbSet<UserProfit> UserProfits { get; set; }
        public DbSet<UserScore> UserScores { get; set; }
        public DbSet<UsersInfo> UsersInfoes { get; set; }
        public DbSet<UsersRole> UsersRoles { get; set; }
        public DbSet<UserBuyer> UserBuyers { get; set; }
    }
}
