//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public UsersInfo()
        {
            this.EAuthors = new HashSet<EAuthor>();
            this.EBookInfoes = new HashSet<EBookInfo>();
            this.EntityProfits = new HashSet<EntityProfit>();
            this.EProfits = new HashSet<EProfit>();
            this.Orders = new HashSet<Order>();
            this.PlayManages = new HashSet<PlayManage>();
            this.UserComments = new HashSet<UserComment>();
            this.UserHouses = new HashSet<UserHouse>();
            this.UserProfits = new HashSet<UserProfit>();
            this.UserBuyers = new HashSet<UserBuyer>();
        }
    
        public int UserId { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public int Integral { get; set; }
        public string Email { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public int UserRoleId { get; set; }
        public Nullable<int> TicketCount { get; set; }
    
        public virtual ICollection<EAuthor> EAuthors { get; set; }
        public virtual ICollection<EBookInfo> EBookInfoes { get; set; }
        public virtual ICollection<EntityProfit> EntityProfits { get; set; }
        public virtual ICollection<EProfit> EProfits { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PlayManage> PlayManages { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<UserHouse> UserHouses { get; set; }
        public virtual ICollection<UserProfit> UserProfits { get; set; }
        public virtual ICollection<UserBuyer> UserBuyers { get; set; }
        public virtual UsersRole UsersRole { get; set; }
    }
}
