//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friends.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateGroup
    {
        public PrivateGroup()
        {
            this.FriendRelations = new HashSet<FriendRelation>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public int OwnerId { get; set; }
    
        public virtual ICollection<FriendRelation> FriendRelations { get; set; }
        public virtual User User { get; set; }
    }
}
